from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from academies import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', views.login_view, name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout')
    path('', views.dashboard, name='dashboard'),
    path('academies/', views.academy_list, name='academy_list'),
    path('academies/add/', views.academy_create, name='academy_create'),
    path('academies/<int:pk>/edit/', views.academy_update, name='academy_update'),
    path('academies/<int:pk>/delete/', views.academy_delete, name='academy_delete'),
    path('daily-bookings/', views.booking_list, name='booking_list'),
    path('daily-bookings/add/', views.booking_create, name='booking_create'),
    path('daily-bookings/<int:pk>/edit/', views.booking_update, name='booking_update'),
    path('daily-bookings/<int:pk>/delete/', views.booking_delete, name='booking_delete'),
    path('operation/', views.operation_screen, name='operation_screen'),
    path('operation/cancel-day/', views.cancel_operation_day, name='cancel_operation_day'),
    path('operation/card-action/', views.operation_card_action, name='operation_card_action'),
    path('daily-income/', views.daily_income, name='daily_income'),
    path('shareholders/', views.shareholder_list, name='shareholder_list'),
    path('shareholders/add/', views.shareholder_create, name='shareholder_create'),
    path('shareholders/<int:pk>/edit/', views.shareholder_update, name='shareholder_update'),
    path('shareholders/<int:pk>/delete/', views.shareholder_delete, name='shareholder_delete'),
    path('employees/', views.employee_list, name='employee_list'),
    path('employees/add/', views.employee_create, name='employee_create'),
    path('employees/<int:pk>/edit/', views.employee_update, name='employee_update'),
    path('employees/<int:pk>/delete/', views.employee_delete, name='employee_delete'),

    path('general-expenses/', views.general_expenses_home, name='general_expenses_home'),
    path('founding-expenses/', views.founding_expense_list, name='founding_expense_list'),
    path('founding-expenses/add/', views.founding_expense_create, name='founding_expense_create'),
    path('founding-expenses/<int:pk>/edit/', views.founding_expense_update, name='founding_expense_update'),
    path('founding-expenses/<int:pk>/delete/', views.founding_expense_delete, name='founding_expense_delete'),
    path('monthly-expenses/', views.monthly_expense_list, name='monthly_expense_list'),
    path('monthly-expenses/add/', views.monthly_expense_create, name='monthly_expense_create'),
    path('monthly-expenses/<int:pk>/edit/', views.monthly_expense_update, name='monthly_expense_update'),
    path('monthly-expenses/<int:pk>/delete/', views.monthly_expense_delete, name='monthly_expense_delete'),
    path('daily-expenses/', views.daily_expense_list, name='daily_expense_list'),
    path('daily-expenses/add/', views.daily_expense_create, name='daily_expense_create'),
    path('daily-expenses/<int:pk>/edit/', views.daily_expense_update, name='daily_expense_update'),
    path('daily-expenses/<int:pk>/delete/', views.daily_expense_delete, name='daily_expense_delete'),
    path('operating-expenses/', views.operating_expense_list, name='operating_expense_list'),
    path('operating-expenses/add/', views.operating_expense_create, name='operating_expense_create'),
    path('operating-expenses/<int:pk>/edit/', views.operating_expense_update, name='operating_expense_update'),
    path('operating-expenses/<int:pk>/delete/', views.operating_expense_delete, name='operating_expense_delete'),
    path('cafeteria/settings/', views.cafe_settings, name='cafe_settings'),
    path('cafeteria/stock-adjust/', views.cafe_stock_adjust, name='cafe_stock_adjust'),
    path('cafeteria/sale-prices/', views.cafe_sale_prices, name='cafe_sale_prices'),
    path('cafeteria/items/', views.cafe_item_list, name='cafe_item_list'),
    path('cafeteria/items/add/', views.cafe_item_create, name='cafe_item_create'),
    path('cafeteria/items/<int:pk>/edit/', views.cafe_item_update, name='cafe_item_update'),
    path('cafeteria/items/<int:pk>/delete/', views.cafe_item_delete, name='cafe_item_delete'),
    path('cafeteria/purchases/', views.cafe_purchase_list, name='cafe_purchase_list'),
    path('cafeteria/purchases/add/', views.cafe_purchase_create, name='cafe_purchase_create'),
    path('cafeteria/purchases/<int:pk>/edit/', views.cafe_purchase_update, name='cafe_purchase_update'),
    path('cafeteria/purchases/<int:pk>/delete/', views.cafe_purchase_delete, name='cafe_purchase_delete'),
    path('cafeteria/sales/', views.cafe_sale_list, name='cafe_sale_list'),
    path('cafeteria/sales/add/', views.cafe_sale_create, name='cafe_sale_create'),
    path('cafeteria/sales/<int:pk>/edit/', views.cafe_sale_update, name='cafe_sale_update'),
    path('cafeteria/sales/<int:pk>/delete/', views.cafe_sale_delete, name='cafe_sale_delete'),
    path('settings/', views.settings_home, name='settings_home'),
    path('users/', views.user_list, name='user_list'),
    path('users/add/', views.user_create, name='user_create'),
    path('users/<int:pk>/edit/', views.user_update, name='user_update'),
    path('users/<int:pk>/delete/', views.user_delete, name='user_delete'),
    path('settings/jobs/', views.job_title_list, name='job_title_list'),
    path('settings/jobs/add/', views.job_title_create, name='job_title_create'),
    path('settings/jobs/<int:pk>/edit/', views.job_title_update, name='job_title_update'),
    path('settings/jobs/<int:pk>/delete/', views.job_title_delete, name='job_title_delete'),
    path('settings/bonus/', views.bonus_tier_list, name='bonus_tier_list'),
    path('settings/bonus/add/', views.bonus_tier_create, name='bonus_tier_create'),
    path('settings/bonus/<int:pk>/edit/', views.bonus_tier_update, name='bonus_tier_update'),
    path('settings/bonus/<int:pk>/delete/', views.bonus_tier_delete, name='bonus_tier_delete'),
    path('reports/', views.reports_home, name='reports_home'),
]
