# Generated by Django 5.2.4 on 2026-06-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الأكاديمية')),
                ('sport_activity', models.CharField(max_length=150, verbose_name='النشاط الرياضي')),
                ('company_name', models.CharField(max_length=200, verbose_name='اسم الشركة')),
                ('manager_name', models.CharField(max_length=200, verbose_name='اسم مدير الأكاديمية')),
                ('manager_national_id', models.CharField(blank=True, max_length=50, verbose_name='الرقم القومي لمدير الأكاديمية')),
                ('manager_phone', models.CharField(max_length=50, verbose_name='رقم الهاتف')),
                ('operation_place', models.CharField(max_length=500, verbose_name='مكان التدريب')),
                ('contract_start_date', models.DateField(verbose_name='بداية التعاقد')),
                ('contract_end_date', models.DateField(verbose_name='نهاية التعاقد')),
                ('subscription_type', models.CharField(default='fixed', max_length=20, verbose_name='نوع الاشتراك')),
                ('monthly_subscription', models.PositiveIntegerField(default=0, verbose_name='قيمة الاشتراك الثابت')),
                ('variable_rent_type', models.CharField(blank=True, max_length=20, verbose_name='نوع القيمة المتغيرة')),
                ('variable_rent_value', models.PositiveIntegerField(default=0, verbose_name='قيمة الإيجار')),
                ('training_days', models.CharField(blank=True, max_length=250, verbose_name='أيام التدريب')),
                ('training_hours', models.TextField(blank=True, verbose_name='ساعات التدريب الأساسية')),
                ('has_extra_hours', models.BooleanField(default=False, verbose_name='إضافة ساعات تدريب إضافية')),
                ('extra_training_days', models.CharField(blank=True, max_length=250, verbose_name='أيام التدريب الإضافية')),
                ('extra_training_place', models.CharField(blank=True, max_length=500, verbose_name='مكان التدريب الإضافي')),
                ('extra_training_hours', models.TextField(blank=True, verbose_name='ساعات التدريب الإضافية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'أكاديمية',
                'verbose_name_plural': 'الأكاديميات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(max_length=100, verbose_name='مكان الحجز')),
                ('booking_date', models.DateField(verbose_name='تاريخ الحجز')),
                ('start_time', models.CharField(max_length=50, verbose_name='من الساعة')),
                ('end_time', models.CharField(max_length=50, verbose_name='إلى الساعة')),
                ('customer_name', models.CharField(max_length=200, verbose_name='اسم العميل')),
                ('customer_phone', models.CharField(max_length=50, verbose_name='رقم الموبايل')),
                ('national_id', models.CharField(blank=True, max_length=50, verbose_name='الرقم القومي')),
                ('players_count', models.PositiveIntegerField(default=1, verbose_name='عدد اللاعبين')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='قيمة الحجز')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'حجز يومي',
                'verbose_name_plural': 'الحجز اليومي',
                'ordering': ['-booking_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الموظف')),
                ('national_id', models.CharField(blank=True, max_length=50, verbose_name='الرقم القومي')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('job_title', models.CharField(blank=True, max_length=150, verbose_name='الوظيفة')),
                ('salary', models.PositiveIntegerField(default=0, verbose_name='الراتب')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التعيين')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'موظف',
                'verbose_name_plural': 'الموظفين',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Shareholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المساهم')),
                ('national_id', models.CharField(blank=True, max_length=50, verbose_name='الرقم القومي')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('share_percentage', models.PositiveIntegerField(default=0, verbose_name='نسبة المساهمة %')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مساهم',
                'verbose_name_plural': 'المساهمين',
                'ordering': ['name'],
            },
        ),
    ]
