# Generated by ChatGPT
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0003_academy_security_deposit'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundingExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='بيان مصروف التأسيس')),
                ('expense_date', models.DateField(verbose_name='تاريخ المصروف')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='القيمة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مصروف تأسيس',
                'verbose_name_plural': 'مصروفات التأسيس',
                'ordering': ['-expense_date', 'title'],
            },
        ),
    ]
