# Generated by Django 5.2.4 on 2026-06-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0005_operation_overrides'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(max_length=50, unique=True, verbose_name='كود العميل')),
                ('customer_name', models.CharField(max_length=200, verbose_name='اسم العميل')),
                ('customer_phone', models.CharField(max_length=50, unique=True, verbose_name='رقم الموبايل')),
                ('national_id', models.CharField(blank=True, max_length=50, verbose_name='الرقم القومي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
                'ordering': ['customer_name'],
            },
        ),
        migrations.AddField(
            model_name='dailybooking',
            name='customer_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='كود العميل'),
        ),
    ]
