# Generated by Django 5.2.4 on 2026-07-02 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0010_granular_report_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='اسم الوظيفة')),
                ('base_salary', models.PositiveIntegerField(default=0, verbose_name='أساسي المرتب')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'وظيفة متاحة',
                'verbose_name_plural': 'الوظائف المتاحة',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BonusTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('daily_booking', 'الإيجار اليومي'), ('cafeteria', 'دخل الكافيتريا')], default='daily_booking', max_length=30, verbose_name='نوع الدخل')),
                ('from_amount', models.PositiveIntegerField(default=0, verbose_name='من قيمة')),
                ('to_amount', models.PositiveIntegerField(default=0, verbose_name='حتى قيمة')),
                ('bonus_amount', models.PositiveIntegerField(default=0, verbose_name='قيمة البونص')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_tiers', to='academies.jobtitle', verbose_name='الوظيفة')),
            ],
            options={
                'verbose_name': 'شريحة بونص',
                'verbose_name_plural': 'شرائح البونص',
                'ordering': ['job_title__name', 'source_type', 'from_amount'],
            },
        ),
    ]
