# Generated by Django 5.2.4 on 2026-07-03 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0012_userpermission_job_title_bonus_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='بيان مصروف التشغيل')),
                ('expense_date', models.DateField(verbose_name='تاريخ المصروف')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='قيمة المصروف')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مصروف تشغيل',
                'verbose_name_plural': 'مصروفات التشغيل',
                'ordering': ['-expense_date', 'title'],
            },
        ),
        migrations.RemoveField(
            model_name='userpermission',
            name='job_title',
        ),
    ]
