# Generated by Django 6.0.6 on 2026-07-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0013_operatingexpense_remove_userpermission_job_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyIncomeSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply_date', models.DateField(unique=True, verbose_name='تاريخ التوريد')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='مبلغ التوريد')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'توريد دخل يومي',
                'verbose_name_plural': 'توريدات الدخل اليومي',
                'ordering': ['-supply_date'],
            },
        ),
    ]
