# Generated by Django 6.0.6 on 2026-07-07 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0014_dailyincomesupply'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(default='EESS Management System', max_length=200, verbose_name='اسم البرنامج')),
                ('company_name', models.CharField(default='Egyptian English Sports Services', max_length=250, verbose_name='اسم الشركة')),
                ('company_logo', models.FileField(blank=True, upload_to='branding/', verbose_name='لوجو الشركة')),
                ('main_screen_image', models.FileField(blank=True, upload_to='branding/', verbose_name='صورة الشاشة الرئيسية')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات البرنامج',
                'verbose_name_plural': 'إعدادات البرنامج',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الفرع')),
                ('location', models.CharField(blank=True, max_length=250, verbose_name='الموقع')),
                ('logo', models.FileField(blank=True, upload_to='branches/logos/', verbose_name='لوجو الفرع')),
                ('image', models.FileField(blank=True, upload_to='branches/images/', verbose_name='صورة الفرع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'فرع',
                'verbose_name_plural': 'الأفرع',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SportActivityMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الرياضة / النشاط')),
                ('image', models.FileField(blank=True, upload_to='sports/', verbose_name='الصورة')),
                ('description', models.TextField(blank=True, verbose_name='وصف مختصر')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'صورة رياضة / نشاط',
                'verbose_name_plural': 'صور الرياضات والأنشطة',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='academy',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academies', to='academies.branch', verbose_name='الفرع'),
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الملعب / الصالة')),
                ('facility_type', models.CharField(choices=[('field', 'ملعب'), ('hall', 'صالة رياضية'), ('other', 'أخرى')], default='field', max_length=20, verbose_name='النوع')),
                ('image', models.FileField(blank=True, upload_to='facilities/', verbose_name='الصورة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='academies.branch', verbose_name='الفرع')),
            ],
            options={
                'verbose_name': 'ملعب / صالة',
                'verbose_name_plural': 'الملاعب والصالات',
                'ordering': ['branch__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AcademyMonthlyRentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='الشهر')),
                ('expected_amount', models.PositiveIntegerField(default=0, verbose_name='الإيجار المستحق')),
                ('paid_amount', models.PositiveIntegerField(default=0, verbose_name='المبلغ المدفوع')),
                ('supplied_amount', models.PositiveIntegerField(default=0, verbose_name='المبلغ المورد للشركة')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الدفع')),
                ('supplied_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التوريد')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_rent_payments', to='academies.academy', verbose_name='الأكاديمية')),
            ],
            options={
                'verbose_name': 'سداد إيجار أكاديمية شهري',
                'verbose_name_plural': 'سدادات إيجارات الأكاديميات الشهرية',
                'ordering': ['month', 'academy__name'],
                'unique_together': {('academy', 'month')},
            },
        ),
    ]
