# Generated by Django 6.0.6 on 2026-07-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0015_appsetting_branch_sportactivitymedia_academy_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academymonthlyrentpayment',
            name='paid_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='المبلغ المسدد'),
        ),
        migrations.AlterField(
            model_name='academymonthlyrentpayment',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ السداد'),
        ),
    ]
