# Generated by Django 6.0.6 on 2026-07-08 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0016_alter_academymonthlyrentpayment_paid_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='اسم النشاط')),
                ('training_places', models.CharField(blank=True, max_length=500, verbose_name='أماكن التدريب المتاحة')),
                ('income_type', models.CharField(choices=[('fixed', 'قيمة ثابتة'), ('variable', 'قيمة متغيرة حسب الأيام والساعات'), ('revenue_share', 'نسبة مشاركة من اشتراكات اللاعبين')], default='fixed', max_length=30, verbose_name='نوع الدخل')),
                ('eess_share_percentage', models.PositiveIntegerField(default=0, verbose_name='نسبة EESS من الاشتراكات %')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'نشاط متاح',
                'verbose_name_plural': 'الأنشطة المتاحة',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='academy',
            name='eess_share_percentage',
            field=models.PositiveIntegerField(default=0, verbose_name='نسبة EESS من اشتراكات اللاعبين %'),
        ),
        migrations.CreateModel(
            name='AcademyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('coach', 'مدرب'), ('admin', 'إداري'), ('player', 'لاعب')], max_length=20, verbose_name='النوع')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='رقم الهاتف')),
                ('national_id', models.CharField(blank=True, max_length=50, verbose_name='الرقم القومي')),
                ('monthly_subscription', models.PositiveIntegerField(default=0, verbose_name='الاشتراك الشهري للاعب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='academies.academy', verbose_name='الأكاديمية')),
            ],
            options={
                'verbose_name': 'عضو أكاديمية',
                'verbose_name_plural': 'مدربين وإداريين ولاعبين الأكاديميات',
                'ordering': ['academy__name', 'role', 'name'],
            },
        ),
    ]
