# Generated by Django 6.0.6 on 2026-07-10 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0017_activity_academy_eess_share_percentage_academymember'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeteriaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(unique=True, verbose_name='كود الفئة')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='اسم الفئة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'فئة صنف كافيتريا',
                'verbose_name_plural': 'فئات أصناف الكافيتريا',
                'ordering': ['code', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='cafeteriaitem',
            options={'ordering': ['category__code', 'code', 'name'], 'verbose_name': 'صنف كافيتريا', 'verbose_name_plural': 'أصناف الكافيتريا'},
        ),
        migrations.AddField(
            model_name='cafeteriaitem',
            name='code',
            field=models.PositiveIntegerField(default=0, verbose_name='كود الصنف'),
        ),
        migrations.AddField(
            model_name='cafeteriaitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='academies.cafeteriacategory', verbose_name='فئة الصنف'),
        ),
        migrations.AlterUniqueTogether(
            name='cafeteriaitem',
            unique_together={('category', 'code')},
        ),
    ]
