# Generated by Django 6.0.6 on 2026-07-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0018_cafeteriacategory_alter_cafeteriaitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='daily_rent',
            field=models.PositiveIntegerField(default=0, verbose_name='قيمة إيجار اليوم'),
        ),
        migrations.AddField(
            model_name='facility',
            name='hourly_rent',
            field=models.PositiveIntegerField(default=0, verbose_name='قيمة إيجار الساعة'),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='button_permissions',
            field=models.JSONField(blank=True, default=dict, verbose_name='صلاحيات أزرار الموديولات'),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='can_academy_rent',
            field=models.BooleanField(default=False, verbose_name='إيجارات الأكاديميات'),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='can_accounts',
            field=models.BooleanField(default=False, verbose_name='الحسابات'),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='can_daily_income',
            field=models.BooleanField(default=False, verbose_name='الدخل اليومي / الشهري'),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='can_settings',
            field=models.BooleanField(default=False, verbose_name='الإعدادات'),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='report_permissions',
            field=models.JSONField(blank=True, default=dict, verbose_name='صلاحيات أنواع التقارير'),
        ),
    ]
