# Generated by Django 6.0.6 on 2026-07-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0019_facility_daily_rent_facility_hourly_rent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy',
            name='training_schedule',
            field=models.JSONField(blank=True, default=list, verbose_name='جدول التدريب التفصيلي'),
        ),
    ]
