# Generated by Django 6.0.6 on 2026-07-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0035_appsetting_company_short_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title_ar', models.CharField(default='نصنع أبطال المستقبل', max_length=250, verbose_name='العنوان الرئيسي بالعربية')),
                ('hero_title_en', models.CharField(default="Building Tomorrow's Champions", max_length=250, verbose_name='العنوان الرئيسي بالإنجليزية')),
                ('hero_text', models.TextField(blank=True, verbose_name='النص التعريفي الرئيسي')),
                ('about_title', models.CharField(default='رياضة باحترافية.. مستقبل بلا حدود', max_length=250, verbose_name='عنوان نبذة الشركة')),
                ('about_text', models.TextField(blank=True, verbose_name='نبذة عن الشركة')),
                ('hero_image', models.FileField(blank=True, upload_to='website/', verbose_name='صورة الواجهة الرئيسية')),
                ('about_image', models.FileField(blank=True, upload_to='website/', verbose_name='صورة قسم نبذة عنا')),
                ('phone', models.CharField(blank=True, max_length=60, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='العنوان')),
                ('whatsapp', models.CharField(blank=True, max_length=60, verbose_name='رقم واتساب')),
                ('facebook_url', models.URLField(blank=True, verbose_name='رابط فيسبوك')),
                ('instagram_url', models.URLField(blank=True, verbose_name='رابط إنستجرام')),
                ('youtube_url', models.URLField(blank=True, verbose_name='رابط يوتيوب')),
                ('footer_text', models.CharField(blank=True, max_length=300, verbose_name='نص أسفل الموقع')),
                ('is_published', models.BooleanField(default=True, verbose_name='نشر الموقع للزوار')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات الموقع الإلكتروني',
                'verbose_name_plural': 'إعدادات الموقع الإلكتروني',
            },
        ),
        migrations.AddField(
            model_name='academy',
            name='is_published_on_website',
            field=models.BooleanField(default=True, verbose_name='إظهار الأكاديمية على الموقع'),
        ),
        migrations.AddField(
            model_name='academy',
            name='website_description',
            field=models.TextField(blank=True, verbose_name='نبذة الأكاديمية على الموقع'),
        ),
        migrations.AddField(
            model_name='academymember',
            name='is_published_on_website',
            field=models.BooleanField(default=True, verbose_name='إظهار العضو على الموقع'),
        ),
        migrations.AddField(
            model_name='academymember',
            name='website_bio',
            field=models.TextField(blank=True, verbose_name='نبذة المدرب على الموقع'),
        ),
        migrations.AddField(
            model_name='branch',
            name='is_published_on_website',
            field=models.BooleanField(default=True, verbose_name='إظهار الفرع على الموقع'),
        ),
        migrations.AddField(
            model_name='branch',
            name='website_description',
            field=models.TextField(blank=True, verbose_name='نبذة الفرع على الموقع'),
        ),
        migrations.AddField(
            model_name='shareholder',
            name='is_published_on_website',
            field=models.BooleanField(default=True, verbose_name='إظهار العضو على الموقع'),
        ),
        migrations.AddField(
            model_name='shareholder',
            name='job_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='الوظيفة / الصفة بمجلس الإدارة'),
        ),
        migrations.AddField(
            model_name='shareholder',
            name='photo_content_type',
            field=models.CharField(blank=True, editable=False, max_length=100, verbose_name='نوع ملف الصورة'),
        ),
        migrations.AddField(
            model_name='shareholder',
            name='photo_data',
            field=models.BinaryField(blank=True, null=True, verbose_name='بيانات الصورة'),
        ),
        migrations.AddField(
            model_name='shareholder',
            name='photo_name',
            field=models.CharField(blank=True, editable=False, max_length=255, verbose_name='اسم ملف الصورة'),
        ),
        migrations.AddField(
            model_name='shareholder',
            name='website_bio',
            field=models.TextField(blank=True, verbose_name='نبذة عضو مجلس الإدارة'),
        ),
    ]
