# Generated by Django 6.0.6 on 2026-07-19 14:33

from django.db import migrations, models


def preserve_existing_media(apps, schema_editor):
    mappings = (
        ('AppSetting', ('company_logo', 'main_screen_image')),
        ('WebsiteSetting', ('hero_image', 'about_image')),
        ('Branch', ('logo', 'image')),
        ('SportActivityMedia', ('image',)),
    )
    for model_name, field_names in mappings:
        model = apps.get_model('academies', model_name)
        for instance in model.objects.all().iterator():
            changed = []
            for field_name in field_names:
                file_value = getattr(instance, field_name, None)
                if not file_value or getattr(instance, f'{field_name}_data', None):
                    continue
                try:
                    file_value.open('rb')
                    data = file_value.read()
                    file_value.close()
                except (FileNotFoundError, OSError, ValueError):
                    continue
                if not data:
                    continue
                name = getattr(file_value, 'name', '') or ''
                extension = name.rsplit('.', 1)[-1].lower() if '.' in name else ''
                content_type = {
                    'png': 'image/png',
                    'gif': 'image/gif',
                    'webp': 'image/webp',
                    'svg': 'image/svg+xml',
                }.get(extension, 'image/jpeg')
                setattr(instance, f'{field_name}_data', data)
                setattr(instance, f'{field_name}_content_type', content_type)
                setattr(instance, f'{field_name}_name', name.rsplit('/', 1)[-1])
                changed.extend((
                    f'{field_name}_data',
                    f'{field_name}_content_type',
                    f'{field_name}_name',
                ))
            if changed:
                instance.save(update_fields=changed)


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0038_backfill_public_english_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsetting',
            name='company_logo_content_type',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='appsetting',
            name='company_logo_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appsetting',
            name='company_logo_name',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='appsetting',
            name='main_screen_image_content_type',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='appsetting',
            name='main_screen_image_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appsetting',
            name='main_screen_image_name',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='branch',
            name='image_content_type',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='branch',
            name='image_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='image_name',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='branch',
            name='logo_content_type',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='branch',
            name='logo_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='logo_name',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='sportactivitymedia',
            name='image_content_type',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='sportactivitymedia',
            name='image_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sportactivitymedia',
            name='image_name',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='about_image_content_type',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='about_image_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='about_image_name',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='hero_image_content_type',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='hero_image_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='hero_image_name',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.RunPython(preserve_existing_media, migrations.RunPython.noop),
    ]
