# Generated by Django 6.0.6 on 2026-07-28 14:36

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0046_academyrentpaymententry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeteriaHospitality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=200, verbose_name='اسم الموظف المستلم')),
                ('hospitality_date', models.DateField(default=datetime.date.today, verbose_name='تاريخ الضيافة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cafeteria_hospitality_movements', to='academies.shareholder', verbose_name='عضو مجلس الإدارة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cafeteria_hospitality_movements', to=settings.AUTH_USER_MODEL, verbose_name='سجل بواسطة')),
            ],
            options={
                'verbose_name': 'حركة ضيافة كافيتريا',
                'verbose_name_plural': 'حركات ضيافة الكافيتريا',
                'ordering': ['-hospitality_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CafeteriaHospitalityItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.PositiveIntegerField(default=0, verbose_name='كود الصنف وقت الحركة')),
                ('item_name', models.CharField(max_length=200, verbose_name='اسم الصنف وقت الحركة')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('unit_price', models.PositiveIntegerField(default=0, verbose_name='سعر البيع وقت الحركة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospitality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='academies.cafeteriahospitality', verbose_name='حركة الضيافة')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospitality_items', to='academies.cafeteriaitem', verbose_name='الصنف')),
            ],
            options={
                'verbose_name': 'صنف حركة ضيافة',
                'verbose_name_plural': 'أصناف حركات الضيافة',
                'ordering': ['id'],
            },
        ),
    ]
