# Generated by Django 6.0.6 on 2026-08-08 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0049_cafeteria_operating_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeteriaAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='اسم الإضافة')),
                ('sale_price', models.PositiveIntegerField(default=0, verbose_name='سعر البيع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'إضافة كافيتريا',
                'verbose_name_plural': 'إضافات الكافيتريا',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='cafeteriahospitalityitem',
            name='addon_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='اسم الإضافة وقت الحركة'),
        ),
        migrations.AddField(
            model_name='cafeteriahospitalityitem',
            name='addon_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='كمية الإضافة'),
        ),
        migrations.AddField(
            model_name='cafeteriahospitalityitem',
            name='addon_unit_price',
            field=models.PositiveIntegerField(default=0, verbose_name='سعر الإضافة وقت الحركة'),
        ),
        migrations.AddField(
            model_name='cafeteriasale',
            name='addon_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='اسم الإضافة وقت البيع'),
        ),
        migrations.AddField(
            model_name='cafeteriasale',
            name='addon_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='كمية الإضافة'),
        ),
        migrations.AddField(
            model_name='cafeteriasale',
            name='addon_unit_price',
            field=models.PositiveIntegerField(default=0, verbose_name='سعر الإضافة وقت البيع'),
        ),
        migrations.AddField(
            model_name='cafeteriasale',
            name='addon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='academies.cafeteriaaddon', verbose_name='الإضافة'),
        ),
    ]
