# Generated by Django 6.0.6 on 2026-08-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0054_facilitygalleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='image_content_type',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='facility',
            name='image_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='image_name',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
