# Generated by Django 6.0.6 on 2026-08-24 14:35

import django.db.models.deletion
from datetime import date

from django.db import migrations, models


def copy_current_player_subscriptions(apps, schema_editor):
    AcademyMember = apps.get_model('academies', 'AcademyMember')
    MonthlySubscription = apps.get_model('academies', 'AcademyPlayerMonthlySubscription')
    today = date.today()
    month = date(today.year, today.month, 1)
    rows = [
        MonthlySubscription(
            player_id=player.pk,
            month=month,
            expected_amount=player.monthly_subscription,
            paid_amount=0,
        )
        for player in AcademyMember.objects.filter(
            role='player',
            monthly_subscription__gt=0,
        )
    ]
    MonthlySubscription.objects.bulk_create(rows, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0055_facility_primary_image_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyPlayerMonthlySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='الشهر')),
                ('expected_amount', models.PositiveIntegerField(default=0, verbose_name='مبلغ الاشتراك')),
                ('paid_amount', models.PositiveIntegerField(default=0, verbose_name='المبلغ المسدد')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(limit_choices_to={'role': 'player'}, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_subscriptions', to='academies.academymember', verbose_name='اللاعب')),
            ],
            options={
                'verbose_name': 'اشتراك شهري للاعب',
                'verbose_name_plural': 'الاشتراكات الشهرية للاعبين',
                'ordering': ['month', 'player__name'],
                'constraints': [models.UniqueConstraint(fields=('player', 'month'), name='unique_player_monthly_subscription')],
            },
        ),
        migrations.RunPython(copy_current_player_subscriptions, migrations.RunPython.noop),
    ]
