# Generated by Django 6.0.6 on 2026-09-02 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0057_cafeteria_staff_prices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('reward', 'المكافآت'), ('deduction', 'الخصومات'), ('advance', 'السلف')], max_length=12, verbose_name='نوع الحركة')),
                ('month', models.DateField(verbose_name='الشهر والسنة')),
                ('amount', models.PositiveIntegerField(verbose_name='المبلغ')),
                ('reason', models.CharField(max_length=500, verbose_name='السبب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_adjustments', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_adjustments', to='academies.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'حركة مرتب',
                'verbose_name_plural': 'حركات المرتبات',
                'ordering': ['-month', '-created_at', '-pk'],
                'indexes': [models.Index(fields=['month', 'employee'], name='payroll_month_employee_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payroll_adjustment_positive_amount'), models.CheckConstraint(condition=models.Q(('kind__in', ['reward', 'deduction', 'advance'])), name='payroll_adjustment_valid_kind')],
            },
        ),
    ]
