# Generated by Django 6.0.6 on 2026-09-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0058_payroll_adjustments'),
    ]

    operations = [
        migrations.AddField(
            model_name='academyplayermonthlysubscription',
            name='supplied_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='المبلغ المورد للشركة'),
        ),
        migrations.AddConstraint(
            model_name='academyplayermonthlysubscription',
            constraint=models.CheckConstraint(condition=models.Q(('supplied_amount__lte', models.F('paid_amount'))), name='player_sub_supply_lte_paid'),
        ),
    ]
