# Generated by Django 6.0.6 on 2026-09-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0059_player_subscription_supplied_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='academyplayermonthlysubscription',
            name='supply_is_recorded',
            field=models.BooleanField(default=False, verbose_name='تم تسجيل المبلغ المورد'),
        ),
    ]
