# Generated by Django 6.0.6 on 2026-09-13 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0060_preserve_legacy_academy_supply'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyTrainingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المجموعة')),
                ('training_days', models.JSONField(default=list, verbose_name='أيام التدريب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_groups', to='academies.academy', verbose_name='الأكاديمية')),
            ],
            options={
                'verbose_name': 'مجموعة تدريب',
                'verbose_name_plural': 'مجموعات التدريب',
                'ordering': ['academy__name', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AcademyTrainingGroupPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_assignments', to='academies.academytraininggroup', verbose_name='المجموعة')),
                ('player', models.ForeignKey(limit_choices_to={'role': 'player'}, on_delete=django.db.models.deletion.CASCADE, related_name='group_assignments', to='academies.academymember', verbose_name='اللاعب')),
            ],
            options={
                'verbose_name': 'تسكين لاعب في مجموعة',
                'verbose_name_plural': 'تسكين اللاعبين في المجموعات',
                'ordering': ['player__name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='academytraininggroup',
            name='players',
            field=models.ManyToManyField(related_name='training_groups', through='academies.AcademyTrainingGroupPlayer', to='academies.academymember', verbose_name='اللاعبون'),
        ),
        migrations.AddConstraint(
            model_name='academytraininggroupplayer',
            constraint=models.UniqueConstraint(fields=('group', 'player'), name='unique_player_in_training_group'),
        ),
        migrations.AddConstraint(
            model_name='academytraininggroup',
            constraint=models.UniqueConstraint(fields=('academy', 'name'), name='unique_academy_training_group_name'),
        ),
    ]
