# Generated by Django 6.0.6 on 2026-09-13 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0061_academy_training_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyTrainingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(verbose_name='تاريخ التدريب')),
                ('is_present', models.BooleanField(default=False, verbose_name='حاضر')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='academies.academytraininggroup', verbose_name='المجموعة')),
                ('player', models.ForeignKey(limit_choices_to={'role': 'player'}, on_delete=django.db.models.deletion.CASCADE, related_name='training_attendance_records', to='academies.academymember', verbose_name='اللاعب')),
            ],
            options={
                'verbose_name': 'حضور لاعب',
                'verbose_name_plural': 'حضور وغياب اللاعبين',
                'ordering': ['attendance_date', 'player__name', 'id'],
                'constraints': [models.UniqueConstraint(fields=('group', 'player', 'attendance_date'), name='unique_group_player_attendance_date')],
            },
        ),
    ]
