# Generated by Django 6.0.6 on 2026-09-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0062_academy_training_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='academytraininggroup',
            name='training_times',
            field=models.JSONField(blank=True, default=dict, verbose_name='مواعيد التدريب'),
        ),
    ]
