# Generated by Django 6.0.6 on 2026-09-13 14:32

from django.db import migrations, models


def copy_legacy_fixed_rents(apps, schema_editor):
    Academy = apps.get_model('academies', 'Academy')
    for academy in Academy.objects.filter(subscription_type='fixed').iterator():
        academy.fixed_monthly_rents = {
            str(month): int(academy.monthly_subscription or 0)
            for month in range(1, 13)
        }
        academy.save(update_fields=['fixed_monthly_rents'])


class Migration(migrations.Migration):

    dependencies = [
        ('academies', '0063_academy_training_group_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='academy',
            name='fixed_monthly_rents',
            field=models.JSONField(blank=True, default=dict, verbose_name='قيم الإيجار الشهري الثابت'),
        ),
        migrations.RunPython(copy_legacy_fixed_rents, migrations.RunPython.noop),
    ]
